### ISSUE TITLE
Uninformative stack traces

### ISSUE THREAD

**Issue by wryun** [jtblin/syncho#4]
Perhaps something like:

https://github.com/laverdet/node-fibers/blob/master/future.js#L195

would help?

**Comment by jtblin** [comment]
Thanks for the suggestion. Do you have an example of what you mean by the stack trace is uninformative?

**Comment by m1sta** [comment]
Here's an example...

    var sync = require('syncho');
 
    function asyncEcho (text, cb) {
      process.nextTick(function () {
        cb(null, text);
      });
    }
 
    function asyncError (text, cb) {
      process.nextTick(function () {
        cb('Too bad');
      });
    }
 
    sync(function (){
        console.log('Before sync');
        console.log(asyncEcho.sync(null, 'Hello!'));
        console.log('After sync');
        asyncError.sync(null, 'Hello!');
    });

The stack trace that is thrown doesn't immediatley poin to where it all where wrong.

**Comment by wryun** [comment]
syncho vs futures:

```javascript
var Sync = require('syncho');
var obj = {
  asyncError: function (text, cb) {
    process.nextTick(function() {
      cb(new Error('argh'));
    });
  }
};  
  
Sync(function (){
  try {
    obj.asyncError.sync(null, 'Hello!');
  } catch (e) {
    console.log(e.stack);
  } 
});
  
var Future = require('fibers/future');
obj = Future.wrap(obj);
Future.task(function () {
  try {
    obj.asyncErrorFuture('Hello').wait();
  } catch (e) {
    console.log(e.stack);
  }
}).detach();
```

output:
```
Error: argh
    at /Users/jhaggerty/a/other/synchotest/test2.js:5:10
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
Error: argh
    at Object.Future.wait (/Users/jhaggerty/a/other/synchotest/node_modules/fibers/future.js:398:15)
    at /Users/jhaggerty/a/other/synchotest/test2.js:22:35
    at /Users/jhaggerty/a/other/synchotest/node_modules/fibers/future.js:416:21
    - - - - -
    at /Users/jhaggerty/a/other/synchotest/test2.js:5:10
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
```

Note that we see the critical line 22 in futures, whereas in syncho we only see the stack processing the tickCallback.
